from enum import Enum


class ErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    MISSING_FIELD = "MISSING_FIELD"
    INVALID_FIELD = "INVALID_FIELD"

    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_INVALID = "PROVIDER_INVALID"
    PROVIDER_LOAD_FAILED = "PROVIDER_LOAD_FAILED"
    PROVIDER_EXECUTION_FAILED = "PROVIDER_EXECUTION_FAILED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_ENTRY_NOT_FOUND = "PROVIDER_ENTRY_NOT_FOUND"
    PROVIDER_VERSION_NOT_FOUND = "PROVIDER_VERSION_NOT_FOUND"
    PROVIDER_VERSION_IS_NOT_A_DIRECTORY = "PROVIDER_VERSION_IS_NOT_A_DIRECTORY"
    PROVIDER_VERSION_JSON_NOT_FOUND = "PROVIDER_VERSION_JSON_NOT_FOUND"

    MEMORY_LOAD_FAILED = "MEMORY_LOAD_FAILED"
    MEMORY_SAVE_FAILED = "MEMORY_SAVE_FAILED"

    INTERNAL_ERROR = "INTERNAL_ERROR"
    ENGINE_ERROR = "ENGINE_ERROR"

    MESSAGE_TOO_LARGE = "MESSAGE_TOO_LARGE"
